name: Deploy Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Sync PySpark Code to Live Production Notebooks
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Connecting securely to Databricks..."
          
          # Forcefully overwrite the exact notebooks your live Databricks Jobs are using.
          # The '-o' flag ensures the old code is erased and replaced with the new code from VS Code.
          
          databricks workspace import -l PYTHON -o 01_bronze_ingestion_v2.py /Users/mayankgodara87@gmail.com/01_bronze_ingestion_v2
          
          databricks workspace import -l PYTHON -o 02_silver_cleansing_v2.py /Users/mayankgodara87@gmail.com/02_silver_cleansing_v2
          
          databricks workspace import -l PYTHON -o 03_gold_layer_v2 /Users/mayankgodara87@gmail.com/03_gold_layer_v2
          
          echo "Live Production Code Sync is 100% Complete!"
      - name: Execute Metadata DB Updates
        env:
          DATABRICKS_HOST: https://dbc-7ac681c6-384b.cloud.databricks.com
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Executing version-controlled SQL update script..."
          databricks statement-execution execute-statement "c00b24f41bdae4c7" --statement "$(cat metadata_admin/change_scd_strategy.sql)" --wait