name: Deploy Data Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Sync PySpark Code to Live Production Notebooks
        env:
          DATABRICKS_HOST: https://dbc-7ac681c6-384b.cloud.databricks.com
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Connecting securely to Databricks..."
          
          # Forcefully upload Silver Layer
          databricks workspace import /Users/mayankgodara87@gmail.com/02_silver_cleansing_v2 --file 02_silver_cleansing_v2.py --language PYTHON --overwrite
          
          # Forcefully upload Gold Layer (Notice the missing .py here to match your repo!)
          databricks workspace import /Users/mayankgodara87@gmail.com/03_gold_layer_v2 --file 03_gold_layer_v2.py --language PYTHON --overwrite
          
          echo "Live Production Code Sync is 100% Complete!"

      - name: Execute Metadata DB Updates
        env:
          DATABRICKS_HOST: https://dbc-7ac681c6-384b.cloud.databricks.com
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "Executing version-controlled SQL update script..."
          databricks statement-execution execute-statement "c00b24f41bdae4c7" --statement "$(cat metadata_admin/change_scd_strategy.sql)" --wait